spring:
  application:
    name: StGuideBook
  datasource:
    url: com.mysql.cj.jdbc.Driver
    username: localmaster
    password: ChoiDoHyun
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  logging:
    level:
      root:DEBUG
